# Site settings
title: "Tech Titans - FLL Team"
description: "Tech Titans FLL Team from Eagle Ridge Middle School, Ashburn, Virginia"
url: "https://tech-titans-fll.github.io"
baseurl: "/tech-titans"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Team Info
team:
  name: "Tech Titans"
  full_name: "Tech Titans First LEGO League"
  season: "2024-25"
  school: "Eagle Ridge Middle School"
  location: "Ashburn, Virginia"
  meeting:
    location: "Brambleton Library, Brambleton, Virginia"
    time: "Friday 5:30 PM - 6:30 PM"
  mentors:
    - name: "Venkatesh"
      role: "Lead Mentor"
      organization: "Robotics for Youth Virginia"
      link: "https://roboticsforyouth.org" # You'll need to find the actual link
    - name: "Shyam Bhagwat"
      role: "Co-Mentor"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
include: ["_pages"]