# Site settings
title: "Tech Titans - FIRST LEGO League"
description: "Official website of Tech Titans FLL Team"
url: "https://tech-titans-fll.github.io"
baseurl: "/tech-titans"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Team Info
team:
  name: "Tech Titans"
  season: "2024-25"
  mentor:
    name: "Your Name"
    email: "your.email@example.com"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
include: ["_pages"]